### PR TITLE
GEOM-32: include sources of core

### PR DESCRIPTION
**Pull request by janvenstermans**
sources are needed in client code of other projects.

### CODE REVIEW

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by hkristof** [comment]
Kristof: +1 (binding) 
= _ =

**Comment by janvenstermans** [comment]
jan Venstermans: +1

**Comment by janvenstermans** [comment]
Vote successful:
Oliver May: +1 (binding)
Kristof: +1 (binding) = _ =

Jan Venstermans: +1

**Pull request merged**
